---
title: "Skin Conductance Response Deconvolution using Hierarchical Bayesian Posterior Estimation"
author: "Benedikt Ehinger & Selim Onat"
date: "`r format(Sys.time(), '%d %B, %Y')`"
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, autodep=T,message=FALSE,cache=T,fig.width=12, fig.height=4) #usually fig height 8
```

```{r set-options, echo=FALSE, cache=FALSE}
options(width = 120)
```

```{r loadData}
library(ggplot2)
library(rstan)
library(plyr)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
source('generate_scr_data.R')
source('scr_model.R')
source('scr_load_data.R')
# Generate Fake Data
#set.seed(1)
cfg = list(resample_to_fs =2,
           orgsamplingrate=10,
           plot=T)
```
This is all the data of the baseline condition we want to model. I remove all data 20s after the last stimulus onset, we don't want to model it.

```{r select one and downsample}
source('scr_get_stan_data.R')
data = scr_get_stan_data(cfg)
```
We take one subect, in this case subject: `r show(selectSub)`, we downsample the data to 1Hz

```{r prepare stan,fig.height=12}
model_2 <- stan_model(file = 'scr_model_2_hierarchicalonset.stan')

```

```{r fit stan}
parstosave = c('m_latency','s_latency','latency','m_amp','s_amp','m_amp_sigma','s_amp_sigma','amp','amp_sigma','amp_per_onset','m_tau1','s_tau1','tau1','m_tau2','s_tau2','tau2','m_scr_sigma','s_scr_sigma','scr_sigma')

fit <- sampling(model_2,
                data = data$data_stan, 
                algorithm='NUTS',
                iter = 1000,
                init = list(data$init.f()),
                chains = 1,
                refresh=10,
                pars=parstosave,
                control=list(adapt_delta=0.5))

source('scr_stan_grid_collect.R')
#fit = scr_stan_grid_collect(name='2015-11-27_scr_model_2_hierarchicalonset_adaptdelta0.98')
#grid engine saving
#save(fit,file= file.path(dir,name))
```

```{r plot some mcmc plots}
# Plotting

traceplot(fit,pars=c('m_amp','m_latency','m_tau1','m_tau2','m_scr_sigma'),inc_warmup=T)
traceplot(fit,pars=c('s_amp','s_latency','s_tau1','s_tau2','s_scr_sigma'),inc_warmup=T)

sub = 2
traceplot(fit,pars=laply(c('amp[%d,1]','latency[%d,1]','tau1[%d]','tau2[%d]','scr_sigma[%d]'),.fun=function(x)sprintf(x,sub)),inc_warmup=T)

traceplot(fit,pars=laply('amp_per_onset[1,2]',.fun=function(x)sprintf(x,sub)),inc_warmup=T)
S = ggmcmc::ggs(fit)
ggmcmc::ggs_autocorrelation(S)
ggmcmc::ggs_caterpillar(S)

```
There is huge autocorrelation, the model most likely did not converge perfectly. But for now I'm happy with it.

```{r posterior predictive}
# Evaluate Fit
a = NULL
S$IterationUnique = as.numeric(interaction(S$Iteration,S$Chain))
for (idx in sample.int(max(S$IterationUnique),100)){
  amplist = NULL
  for( o in 1:data_stan$ntrial){
    amplist = c(amplist,S$value[S$IterationUnique == idx& S$Parameter == paste0('amp_per_onset.1.',o,'.')])
  }
  scr = scr_model(x=data_stan$x,onsets = data_stan$onset,latency = rep(S$value[S$IterationUnique == idx & S$Parameter=='latency.1.'],data_stan$ntrial),
                  amp = amplist,
                  tau1 = S$value[S$IterationUnique == idx & S$Parameter=='tau1'],
                  tau2 = S$value[S$IterationUnique == idx & S$Parameter=='tau2'])
  a = rbind(a,data.frame(iter = idx,type='post',time=data_stan$x,scr=scr))
}

source('posterior_predictive.R')
#a = data.frame(posterior_predictive_single(fit,1:data_stan$ntime,onsets=data.frame(onset=data_stan$onset,condition=1)))
a$time = a$time/(cfg$resample_to_fs)
b = rbind.fill(cbind(a,type='post'),cbind(data.scrSL.resamp,type='raw'))
b = cbind(b,alpha <- ifelse(b$type=='post', 0.1, 1))

ggplot(b,aes(x=time,y=scr,colour=type,group=iter))+geom_line(aes(alpha=alpha))
#ggplot(b,aes(x=time,y=scr,colour=type))+stat_summary(fun.ymin="min",fun.ymax="max",fun.y=median,geom='errorbar')+geom_line()

```
